name: example
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 209371
          schedule-id: 100004
          seat-id: 1_0
          slack-incoming-webhook-url: 'https://hooks.slack.com/services/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'
          message: '<@U4CF18RKL> 티켓사세요'
